import type { Category, Mentor } from "./types";

export const categories: Category[] = [
  {
    id: "digital-marketing",
    slug: "digital-marketing",
    title: "Digital Marketing",
    topicCount: 12,
    materialCount: 152,
    description:
      "Kuasai seluruh ekosistem Digital Marketing dari strategi brand, content creation, media berbayar, hingga analitik. Dirancang oleh praktisi industri untuk menghasilkan marketer yang siap kerja.",
    tutorQuote:
      "Modul ini dirancang agar kamu tidak hanya paham teori, tapi langsung bisa menerapkan strategi marketing yang terukur di dunia nyata.",
    tutorName: "Ahmad Fauzi",
    tutorRole: "Senior Digital Marketing Strategist",
    infoCards: [
      {
        title: "Materi",
        description:
          "152 materi video berkualitas tinggi mencakup strategi marketing, brand building, iklan berbayar, SEO, analytics, dan lebih banyak lagi.",
      },
      {
        title: "Praktik",
        description:
          "Worksheet, case study nyata, dan proyek portfolio yang bisa langsung kamu tampilkan ke calon employer atau klien.",
      },
      {
        title: "Benefit",
        description:
          "Akses seumur hidup ke materi, sertifikat resmi Jago Akademi, dan keanggotaan komunitas Digital Marketer Indonesia.",
      },
      {
        title: "Persyaratan",
        description:
          "Tidak ada prasyarat khusus. Cocok untuk pemula hingga profesional yang ingin memperdalam keahlian digital marketing.",
      },
    ],
    topics: [
      {
        id: "marketing-management",
        slug: "marketing-management",
        title: "Marketing Management",
        lessonCount: 12,
        videoCount: 39,
        lessons: [
          {
            id: "marketing-introduction",
            slug: "marketing-introduction",
            title: "Marketing Introduction",
            number: 1,
            chapterCount: 5,
            studentCount: "66.396",
            rating: 4.67,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "mi-1", slug: "apa-itu-marketing", title: "Apa itu Marketing?", durationMinutes: 8, isLocked: true },
              { id: "mi-2", slug: "evolusi-marketing", title: "Evolusi Marketing dari 1.0 ke 5.0", durationMinutes: 10, isLocked: true },
              { id: "mi-3", slug: "marketing-mix", title: "Marketing Mix: 4P dan 7P", durationMinutes: 12, isLocked: true },
              { id: "mi-4", slug: "market-segmentation", title: "Market Segmentation", durationMinutes: 9, isLocked: true },
              { id: "mi-5", slug: "marketing-funnel", title: "Marketing Funnel", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "branding-introduction",
            slug: "branding-introduction",
            title: "Branding Introduction",
            number: 2,
            chapterCount: 5,
            studentCount: "36.213",
            rating: 4.63,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "bi-1", slug: "apa-itu-brand", title: "Apa itu Brand?", durationMinutes: 7, isLocked: true },
              { id: "bi-2", slug: "brand-identity", title: "Brand Identity vs Brand Image", durationMinutes: 9, isLocked: true },
              { id: "bi-3", slug: "brand-equity", title: "Brand Equity", durationMinutes: 11, isLocked: true },
              { id: "bi-4", slug: "brand-architecture", title: "Brand Architecture", durationMinutes: 8, isLocked: true },
              { id: "bi-5", slug: "brand-storytelling", title: "Brand Storytelling", durationMinutes: 12, isLocked: true },
            ],
          },
          {
            id: "brand-positioning",
            slug: "brand-positioning",
            title: "Brand Positioning",
            number: 3,
            chapterCount: 3,
            studentCount: "24.449",
            rating: 4.62,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "bp-1", slug: "positioning-statement", title: "Positioning Statement", durationMinutes: 10, isLocked: true },
              { id: "bp-2", slug: "competitive-differentiation", title: "Competitive Differentiation", durationMinutes: 13, isLocked: true },
              { id: "bp-3", slug: "perceptual-mapping", title: "Perceptual Mapping", durationMinutes: 9, isLocked: true },
            ],
          },
          {
            id: "finding-brand-benefit",
            slug: "finding-brand-benefit",
            title: "Finding the Brand Benefit",
            number: 4,
            chapterCount: 3,
            studentCount: "18.359",
            rating: 4.63,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "fbb-1", slug: "functional-vs-emotional", title: "Functional vs Emotional Benefit", durationMinutes: 11, isLocked: true },
              { id: "fbb-2", slug: "benefit-ladder", title: "Benefit Ladder Framework", durationMinutes: 14, isLocked: true },
              { id: "fbb-3", slug: "usp-development", title: "USP Development", durationMinutes: 10, isLocked: true },
            ],
          },
          {
            id: "consumer-audience-insight",
            slug: "consumer-audience-insight",
            title: "Consumer & Audience Insight",
            number: 5,
            chapterCount: 3,
            studentCount: "16.695",
            rating: 4.61,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "cai-1", slug: "consumer-behavior", title: "Consumer Behavior", durationMinutes: 12, isLocked: true },
              { id: "cai-2", slug: "audience-research", title: "Audience Research Methods", durationMinutes: 15, isLocked: true },
              { id: "cai-3", slug: "persona-development", title: "Persona Development", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "content-marketing",
            slug: "content-marketing",
            title: "Content Marketing",
            number: 6,
            chapterCount: 2,
            studentCount: "15.175",
            rating: 4.64,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "cm-1", slug: "content-strategy", title: "Content Strategy Framework", durationMinutes: 14, isLocked: true },
              { id: "cm-2", slug: "content-calendar", title: "Content Calendar & Distribution", durationMinutes: 13, isLocked: true },
            ],
          },
          {
            id: "campaign-media-planning",
            slug: "campaign-media-planning",
            title: "Campaign & Media Planning",
            number: 7,
            chapterCount: 6,
            studentCount: "13.576",
            rating: 4.64,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "cmp-1", slug: "campaign-brief", title: "Campaign Brief", durationMinutes: 9, isLocked: true },
              { id: "cmp-2", slug: "media-mix", title: "Media Mix Strategy", durationMinutes: 11, isLocked: true },
              { id: "cmp-3", slug: "budget-allocation", title: "Budget Allocation", durationMinutes: 10, isLocked: true },
              { id: "cmp-4", slug: "kpi-setting", title: "KPI Setting", durationMinutes: 8, isLocked: true },
              { id: "cmp-5", slug: "campaign-timeline", title: "Campaign Timeline", durationMinutes: 7, isLocked: true },
              { id: "cmp-6", slug: "performance-review", title: "Performance Review", durationMinutes: 12, isLocked: true },
            ],
          },
          {
            id: "creative-brief-briefing",
            slug: "creative-brief-briefing",
            title: "Creative Brief and Briefing",
            number: 8,
            chapterCount: 2,
            studentCount: "11.006",
            rating: 4.64,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "cbb-1", slug: "creative-brief-anatomy", title: "Anatomy of a Creative Brief", durationMinutes: 13, isLocked: true },
              { id: "cbb-2", slug: "briefing-process", title: "The Briefing Process", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "assessing-marketing-materials",
            slug: "assessing-marketing-materials",
            title: "Assessing Marketing Materials",
            number: 9,
            chapterCount: 4,
            studentCount: "10.822",
            rating: 4.63,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "amm-1", slug: "visual-assessment", title: "Visual Assessment Framework", durationMinutes: 10, isLocked: true },
              { id: "amm-2", slug: "copy-review", title: "Copy Review Checklist", durationMinutes: 9, isLocked: true },
              { id: "amm-3", slug: "brand-consistency", title: "Brand Consistency Check", durationMinutes: 8, isLocked: true },
              { id: "amm-4", slug: "legal-compliance", title: "Legal & Compliance Review", durationMinutes: 7, isLocked: true },
            ],
          },
          {
            id: "creating-integrated-marketing-plan",
            slug: "creating-integrated-marketing-plan",
            title: "Creating Integrated Marketing Plan",
            number: 10,
            chapterCount: 2,
            studentCount: "7.924",
            rating: 4.65,
            isPortfolioProject: true,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "cimp-1", slug: "imc-framework", title: "IMC Framework", durationMinutes: 16, isLocked: true },
              { id: "cimp-2", slug: "marketing-plan-project", title: "Marketing Plan Project", durationMinutes: 20, isLocked: true },
            ],
          },
          {
            id: "brand-creative-strategy",
            slug: "brand-creative-strategy",
            title: "Brand & Creative Strategy",
            number: 11,
            chapterCount: 1,
            studentCount: "6.281",
            rating: 4.66,
            isPortfolioProject: true,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "bcs-1", slug: "brand-strategy-project", title: "Brand Strategy Project", durationMinutes: 25, isLocked: true },
            ],
          },
          {
            id: "brand-campaign",
            slug: "brand-campaign",
            title: "Brand Campaign",
            number: 12,
            chapterCount: 3,
            studentCount: "5.475",
            rating: 4.67,
            isPortfolioProject: true,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "bc-1", slug: "campaign-concept", title: "Campaign Concept Development", durationMinutes: 14, isLocked: true },
              { id: "bc-2", slug: "campaign-execution", title: "Campaign Execution Plan", durationMinutes: 16, isLocked: true },
              { id: "bc-3", slug: "campaign-project", title: "Brand Campaign Project", durationMinutes: 22, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "creative-copywriting",
        slug: "creative-copywriting",
        title: "Creative Copywriting",
        lessonCount: 8,
        videoCount: 24,
        lessons: [
          {
            id: "copywriting-fundamentals",
            slug: "copywriting-fundamentals",
            title: "Copywriting Fundamentals",
            number: 1,
            chapterCount: 4,
            studentCount: "45.123",
            rating: 4.71,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "cf-1", slug: "power-of-words", title: "The Power of Words", durationMinutes: 9, isLocked: true },
              { id: "cf-2", slug: "headline-writing", title: "Headline Writing", durationMinutes: 11, isLocked: true },
              { id: "cf-3", slug: "body-copy", title: "Body Copy Techniques", durationMinutes: 10, isLocked: true },
              { id: "cf-4", slug: "cta-writing", title: "Writing Effective CTAs", durationMinutes: 8, isLocked: true },
            ],
          },
          {
            id: "storytelling-brand",
            slug: "storytelling-brand",
            title: "Storytelling for Brand",
            number: 2,
            chapterCount: 3,
            studentCount: "28.456",
            rating: 4.68,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "sb-1", slug: "brand-narrative", title: "Brand Narrative", durationMinutes: 12, isLocked: true },
              { id: "sb-2", slug: "story-arc", title: "Story Arc for Marketing", durationMinutes: 10, isLocked: true },
              { id: "sb-3", slug: "emotional-copywriting", title: "Emotional Copywriting", durationMinutes: 13, isLocked: true },
            ],
          },
          {
            id: "social-media-copy",
            slug: "social-media-copy",
            title: "Social Media Copy",
            number: 3,
            chapterCount: 3,
            studentCount: "19.874",
            rating: 4.65,
            isPortfolioProject: true,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "smc-1", slug: "instagram-copy", title: "Instagram Caption Formula", durationMinutes: 9, isLocked: true },
              { id: "smc-2", slug: "tiktok-script", title: "TikTok Script Writing", durationMinutes: 11, isLocked: true },
              { id: "smc-3", slug: "copy-project", title: "Social Media Copy Project", durationMinutes: 18, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "social-media-marketing",
        slug: "social-media-marketing",
        title: "Social Media Marketing",
        lessonCount: 10,
        videoCount: 32,
        lessons: [
          {
            id: "sosmed-strategy",
            slug: "sosmed-strategy",
            title: "Social Media Strategy",
            number: 1,
            chapterCount: 4,
            studentCount: "52.341",
            rating: 4.72,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "ss-1", slug: "platform-selection", title: "Platform Selection Strategy", durationMinutes: 10, isLocked: true },
              { id: "ss-2", slug: "content-pillars", title: "Content Pillars", durationMinutes: 9, isLocked: true },
              { id: "ss-3", slug: "posting-schedule", title: "Posting Schedule Optimization", durationMinutes: 8, isLocked: true },
              { id: "ss-4", slug: "engagement-strategy", title: "Engagement Strategy", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "instagram-marketing",
            slug: "instagram-marketing",
            title: "Instagram Marketing",
            number: 2,
            chapterCount: 5,
            studentCount: "38.762",
            rating: 4.69,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "im-1", slug: "instagram-algorithm", title: "Understanding Instagram Algorithm", durationMinutes: 12, isLocked: true },
              { id: "im-2", slug: "reels-strategy", title: "Reels Strategy", durationMinutes: 10, isLocked: true },
              { id: "im-3", slug: "stories-highlights", title: "Stories & Highlights", durationMinutes: 8, isLocked: true },
              { id: "im-4", slug: "ig-shopping", title: "Instagram Shopping Setup", durationMinutes: 9, isLocked: true },
              { id: "im-5", slug: "ig-analytics", title: "Instagram Analytics", durationMinutes: 11, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "campaign-media-planning",
        slug: "campaign-media-planning",
        title: "Campaign and Media Planning",
        lessonCount: 8,
        videoCount: 28,
        lessons: [
          {
            id: "integrated-campaign",
            slug: "integrated-campaign",
            title: "Integrated Campaign Planning",
            number: 1,
            chapterCount: 4,
            studentCount: "22.187",
            rating: 4.64,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "icp-1", slug: "campaign-objectives", title: "Setting Campaign Objectives", durationMinutes: 10, isLocked: true },
              { id: "icp-2", slug: "media-channels", title: "Media Channels Overview", durationMinutes: 12, isLocked: true },
              { id: "icp-3", slug: "reach-frequency", title: "Reach & Frequency", durationMinutes: 9, isLocked: true },
              { id: "icp-4", slug: "campaign-measurement", title: "Campaign Measurement", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "media-buying",
            slug: "media-buying",
            title: "Media Buying Essentials",
            number: 2,
            chapterCount: 3,
            studentCount: "14.532",
            rating: 4.61,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "mb-1", slug: "programmatic-buying", title: "Programmatic Buying", durationMinutes: 13, isLocked: true },
              { id: "mb-2", slug: "direct-buying", title: "Direct Media Buying", durationMinutes: 10, isLocked: true },
              { id: "mb-3", slug: "negotiation-tips", title: "Negotiation Tips", durationMinutes: 8, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "facebook-ads",
        slug: "facebook-ads",
        title: "Facebook Ads",
        lessonCount: 9,
        videoCount: 31,
        lessons: [
          {
            id: "fb-ads-setup",
            slug: "fb-ads-setup",
            title: "Facebook Ads Manager Setup",
            number: 1,
            chapterCount: 4,
            studentCount: "41.234",
            rating: 4.74,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "fas-1", slug: "business-manager", title: "Business Manager Setup", durationMinutes: 12, isLocked: true },
              { id: "fas-2", slug: "pixel-setup", title: "Facebook Pixel Setup", durationMinutes: 10, isLocked: true },
              { id: "fas-3", slug: "audience-types", title: "Audience Types", durationMinutes: 11, isLocked: true },
              { id: "fas-4", slug: "ad-objectives", title: "Ad Objectives Explained", durationMinutes: 9, isLocked: true },
            ],
          },
          {
            id: "fb-targeting",
            slug: "fb-targeting",
            title: "Facebook Targeting Mastery",
            number: 2,
            chapterCount: 3,
            studentCount: "28.913",
            rating: 4.71,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "ft-1", slug: "interest-targeting", title: "Interest & Behavioral Targeting", durationMinutes: 13, isLocked: true },
              { id: "ft-2", slug: "lookalike-audience", title: "Lookalike Audiences", durationMinutes: 11, isLocked: true },
              { id: "ft-3", slug: "retargeting", title: "Retargeting Strategy", durationMinutes: 12, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "tiktok-ads",
        slug: "tiktok-ads",
        title: "TikTok Ads",
        lessonCount: 7,
        videoCount: 22,
        lessons: [
          {
            id: "tiktok-ads-intro",
            slug: "tiktok-ads-intro",
            title: "TikTok Ads Introduction",
            number: 1,
            chapterCount: 3,
            studentCount: "35.678",
            rating: 4.76,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "tai-1", slug: "tiktok-ecosystem", title: "TikTok Ads Ecosystem", durationMinutes: 10, isLocked: true },
              { id: "tai-2", slug: "ad-formats", title: "Ad Formats on TikTok", durationMinutes: 9, isLocked: true },
              { id: "tai-3", slug: "spark-ads", title: "Spark Ads", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "tiktok-creative",
            slug: "tiktok-creative",
            title: "TikTok Creative Strategy",
            number: 2,
            chapterCount: 3,
            studentCount: "22.145",
            rating: 4.73,
            isPortfolioProject: true,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "tc-1", slug: "hook-formula", title: "Hook Formula for TikTok", durationMinutes: 12, isLocked: true },
              { id: "tc-2", slug: "ugc-strategy", title: "UGC Strategy", durationMinutes: 10, isLocked: true },
              { id: "tc-3", slug: "tiktok-creative-project", title: "TikTok Ad Creative Project", durationMinutes: 18, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "google-ads",
        slug: "google-ads",
        title: "Google Ads",
        lessonCount: 10,
        videoCount: 35,
        lessons: [
          {
            id: "google-search-ads",
            slug: "google-search-ads",
            title: "Google Search Ads",
            number: 1,
            chapterCount: 5,
            studentCount: "44.321",
            rating: 4.73,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "gsa-1", slug: "keyword-research", title: "Keyword Research", durationMinutes: 13, isLocked: true },
              { id: "gsa-2", slug: "ad-copy", title: "Ad Copy Writing", durationMinutes: 10, isLocked: true },
              { id: "gsa-3", slug: "bid-strategy", title: "Bid Strategy", durationMinutes: 11, isLocked: true },
              { id: "gsa-4", slug: "quality-score", title: "Quality Score Optimization", durationMinutes: 9, isLocked: true },
              { id: "gsa-5", slug: "search-campaign", title: "Search Campaign Setup", durationMinutes: 14, isLocked: true },
            ],
          },
          {
            id: "google-display",
            slug: "google-display",
            title: "Google Display Network",
            number: 2,
            chapterCount: 3,
            studentCount: "21.876",
            rating: 4.66,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "gd-1", slug: "display-targeting", title: "Display Targeting Options", durationMinutes: 10, isLocked: true },
              { id: "gd-2", slug: "responsive-ads", title: "Responsive Display Ads", durationMinutes: 9, isLocked: true },
              { id: "gd-3", slug: "remarketing", title: "Remarketing Setup", durationMinutes: 11, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "influencer-marketing",
        slug: "influencer-marketing",
        title: "Influencer and Community Marketing",
        lessonCount: 6,
        videoCount: 18,
        lessons: [
          {
            id: "influencer-strategy",
            slug: "influencer-strategy",
            title: "Influencer Marketing Strategy",
            number: 1,
            chapterCount: 4,
            studentCount: "18.543",
            rating: 4.67,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "is-1", slug: "influencer-tiers", title: "Influencer Tiers & Selection", durationMinutes: 11, isLocked: true },
              { id: "is-2", slug: "kol-brief", title: "KOL Brief Creation", durationMinutes: 9, isLocked: true },
              { id: "is-3", slug: "campaign-tracking", title: "Campaign Tracking", durationMinutes: 10, isLocked: true },
              { id: "is-4", slug: "roi-measurement", title: "ROI Measurement", durationMinutes: 8, isLocked: true },
            ],
          },
          {
            id: "community-building",
            slug: "community-building",
            title: "Community Building",
            number: 2,
            chapterCount: 3,
            studentCount: "11.234",
            rating: 4.63,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "cb-1", slug: "community-platforms", title: "Community Platforms", durationMinutes: 9, isLocked: true },
              { id: "cb-2", slug: "engagement-programs", title: "Engagement Programs", durationMinutes: 11, isLocked: true },
              { id: "cb-3", slug: "community-moderation", title: "Community Moderation", durationMinutes: 8, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "google-analytics",
        slug: "google-analytics",
        title: "Google Analytics",
        lessonCount: 8,
        videoCount: 26,
        lessons: [
          {
            id: "ga4-setup",
            slug: "ga4-setup",
            title: "GA4 Setup & Configuration",
            number: 1,
            chapterCount: 4,
            studentCount: "29.876",
            rating: 4.70,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "ga-1", slug: "ga4-intro", title: "Introduction to GA4", durationMinutes: 10, isLocked: true },
              { id: "ga-2", slug: "property-setup", title: "Property Setup", durationMinutes: 12, isLocked: true },
              { id: "ga-3", slug: "event-tracking", title: "Event Tracking", durationMinutes: 14, isLocked: true },
              { id: "ga-4", slug: "custom-dimensions", title: "Custom Dimensions", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "analytics-reporting",
            slug: "analytics-reporting",
            title: "Analytics Reporting",
            number: 2,
            chapterCount: 3,
            studentCount: "19.432",
            rating: 4.68,
            isPortfolioProject: true,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "ar-1", slug: "custom-reports", title: "Custom Reports", durationMinutes: 13, isLocked: true },
              { id: "ar-2", slug: "looker-studio", title: "Looker Studio Integration", durationMinutes: 15, isLocked: true },
              { id: "ar-3", slug: "analytics-project", title: "Analytics Dashboard Project", durationMinutes: 20, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "seo",
        slug: "seo",
        title: "Search Engine Optimization",
        lessonCount: 11,
        videoCount: 38,
        lessons: [
          {
            id: "seo-fundamentals",
            slug: "seo-fundamentals",
            title: "SEO Fundamentals",
            number: 1,
            chapterCount: 5,
            studentCount: "48.123",
            rating: 4.72,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "sf-1", slug: "how-search-works", title: "How Search Engines Work", durationMinutes: 11, isLocked: true },
              { id: "sf-2", slug: "on-page-seo", title: "On-Page SEO", durationMinutes: 13, isLocked: true },
              { id: "sf-3", slug: "off-page-seo", title: "Off-Page SEO", durationMinutes: 10, isLocked: true },
              { id: "sf-4", slug: "technical-seo", title: "Technical SEO Basics", durationMinutes: 14, isLocked: true },
              { id: "sf-5", slug: "seo-tools", title: "SEO Tools Overview", durationMinutes: 9, isLocked: true },
            ],
          },
          {
            id: "keyword-strategy",
            slug: "keyword-strategy",
            title: "Keyword Strategy",
            number: 2,
            chapterCount: 3,
            studentCount: "31.456",
            rating: 4.69,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "ks-1", slug: "keyword-research-seo", title: "Keyword Research for SEO", durationMinutes: 14, isLocked: true },
              { id: "ks-2", slug: "search-intent", title: "Search Intent Analysis", durationMinutes: 12, isLocked: true },
              { id: "ks-3", slug: "keyword-mapping", title: "Keyword Mapping", durationMinutes: 10, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "app-store-optimization",
        slug: "app-store-optimization",
        title: "App Store Optimization",
        lessonCount: 5,
        videoCount: 15,
        lessons: [
          {
            id: "aso-basics",
            slug: "aso-basics",
            title: "ASO Basics",
            number: 1,
            chapterCount: 3,
            studentCount: "12.345",
            rating: 4.63,
            isPortfolioProject: false,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "aso-1", slug: "app-store-factors", title: "App Store Ranking Factors", durationMinutes: 11, isLocked: true },
              { id: "aso-2", slug: "app-title-description", title: "Title & Description Optimization", durationMinutes: 9, isLocked: true },
              { id: "aso-3", slug: "app-visuals", title: "Screenshots & Preview Videos", durationMinutes: 10, isLocked: true },
            ],
          },
          {
            id: "aso-advanced",
            slug: "aso-advanced",
            title: "ASO Advanced Strategies",
            number: 2,
            chapterCount: 2,
            studentCount: "7.891",
            rating: 4.66,
            isPortfolioProject: true,
            mentorId: "ahmad-fauzi",
            chapters: [
              { id: "asoa-1", slug: "ratings-reviews", title: "Ratings & Reviews Strategy", durationMinutes: 12, isLocked: true },
              { id: "asoa-2", slug: "aso-project", title: "ASO Audit Project", durationMinutes: 18, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "customer-relationship-management",
        slug: "customer-relationship-management",
        title: "Customer Relationship Management",
        lessonCount: 7,
        videoCount: 21,
        lessons: [
          {
            id: "crm-introduction",
            slug: "crm-introduction",
            title: "CRM Introduction",
            number: 1,
            chapterCount: 3,
            studentCount: "16.789",
            rating: 4.65,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "crm-1", slug: "crm-concepts", title: "CRM Core Concepts", durationMinutes: 10, isLocked: true },
              { id: "crm-2", slug: "customer-lifecycle", title: "Customer Lifecycle", durationMinutes: 12, isLocked: true },
              { id: "crm-3", slug: "crm-tools", title: "CRM Tools Overview", durationMinutes: 9, isLocked: true },
            ],
          },
          {
            id: "email-marketing",
            slug: "email-marketing",
            title: "Email Marketing",
            number: 2,
            chapterCount: 4,
            studentCount: "24.567",
            rating: 4.70,
            isPortfolioProject: false,
            mentorId: "rina-kusuma",
            chapters: [
              { id: "em-1", slug: "email-strategy", title: "Email Strategy", durationMinutes: 10, isLocked: true },
              { id: "em-2", slug: "segmentation", title: "List Segmentation", durationMinutes: 11, isLocked: true },
              { id: "em-3", slug: "automation-flows", title: "Automation Flows", durationMinutes: 13, isLocked: true },
              { id: "em-4", slug: "email-analytics", title: "Email Analytics", durationMinutes: 9, isLocked: true },
            ],
          },
        ],
      },
    ],
  },

  // === Data Science & Analysis ===
  {
    id: "data-science",
    slug: "data-science",
    title: "Data Science & Analysis",
    topicCount: 8,
    materialCount: 96,
    description:
      "Dari Python dasar hingga machine learning dan visualisasi data. Kuasai skill yang paling dicari di era data-driven business.",
    tutorQuote:
      "Data adalah bahasa bisnis modern. Dengan skill ini, kamu bisa mengambil keputusan lebih cerdas dan membuktikan nilai kerjamu dengan angka.",
    tutorName: "Kevin Wijaya",
    tutorRole: "Senior Data Scientist",
    infoCards: [
      { title: "Materi", description: "96 video dari Python dasar, SQL, statistik, visualisasi data, hingga machine learning." },
      { title: "Praktik", description: "Dataset nyata, proyek analisis, dan dashboard yang bisa langsung dimasukkan ke portfolio." },
      { title: "Benefit", description: "Sertifikat resmi, akses komunitas Data Analyst Indonesia, dan job preparation resources." },
      { title: "Persyaratan", description: "Tidak ada prasyarat. Cocok untuk fresh graduate, career switcher, maupun profesional bisnis." },
    ],
    topics: [
      {
        id: "python-dasar",
        slug: "python-dasar",
        title: "Python untuk Data Analysis",
        lessonCount: 8,
        videoCount: 28,
        lessons: [
          {
            id: "python-intro",
            slug: "python-intro",
            title: "Python Introduction",
            number: 1,
            chapterCount: 4,
            studentCount: "38.456",
            rating: 4.75,
            isPortfolioProject: false,
            mentorId: "kevin-wijaya",
            chapters: [
              { id: "pi-1", slug: "python-basics", title: "Python Basics", durationMinutes: 12, isLocked: true },
              { id: "pi-2", slug: "data-types", title: "Data Types & Structures", durationMinutes: 14, isLocked: true },
              { id: "pi-3", slug: "functions", title: "Functions & Modules", durationMinutes: 11, isLocked: true },
              { id: "pi-4", slug: "pandas-intro", title: "Pandas Introduction", durationMinutes: 13, isLocked: true },
            ],
          },
          {
            id: "data-wrangling",
            slug: "data-wrangling",
            title: "Data Wrangling",
            number: 2,
            chapterCount: 3,
            studentCount: "24.321",
            rating: 4.71,
            isPortfolioProject: false,
            mentorId: "kevin-wijaya",
            chapters: [
              { id: "dw-1", slug: "data-cleaning", title: "Data Cleaning", durationMinutes: 15, isLocked: true },
              { id: "dw-2", slug: "missing-values", title: "Handling Missing Values", durationMinutes: 12, isLocked: true },
              { id: "dw-3", slug: "data-transformation", title: "Data Transformation", durationMinutes: 13, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "sql-analysis",
        slug: "sql-analysis",
        title: "SQL untuk Data Analyst",
        lessonCount: 7,
        videoCount: 24,
        lessons: [
          {
            id: "sql-basics",
            slug: "sql-basics",
            title: "SQL Fundamentals",
            number: 1,
            chapterCount: 4,
            studentCount: "41.234",
            rating: 4.78,
            isPortfolioProject: false,
            mentorId: "kevin-wijaya",
            chapters: [
              { id: "sq-1", slug: "select-query", title: "SELECT Queries", durationMinutes: 10, isLocked: true },
              { id: "sq-2", slug: "joins", title: "JOINs Mastery", durationMinutes: 14, isLocked: true },
              { id: "sq-3", slug: "aggregations", title: "Aggregations & GROUP BY", durationMinutes: 12, isLocked: true },
              { id: "sq-4", slug: "subqueries", title: "Subqueries & CTEs", durationMinutes: 13, isLocked: true },
            ],
          },
          {
            id: "sql-advanced",
            slug: "sql-advanced",
            title: "Advanced SQL",
            number: 2,
            chapterCount: 3,
            studentCount: "18.765",
            rating: 4.72,
            isPortfolioProject: true,
            mentorId: "kevin-wijaya",
            chapters: [
              { id: "sqa-1", slug: "window-functions", title: "Window Functions", durationMinutes: 15, isLocked: true },
              { id: "sqa-2", slug: "performance-tuning", title: "Query Performance Tuning", durationMinutes: 12, isLocked: true },
              { id: "sqa-3", slug: "sql-project", title: "SQL Analysis Project", durationMinutes: 22, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "data-visualization",
        slug: "data-visualization",
        title: "Data Visualization",
        lessonCount: 6,
        videoCount: 20,
        lessons: [
          {
            id: "tableau-basics",
            slug: "tableau-basics",
            title: "Tableau Fundamentals",
            number: 1,
            chapterCount: 4,
            studentCount: "28.912",
            rating: 4.70,
            isPortfolioProject: false,
            mentorId: "kevin-wijaya",
            chapters: [
              { id: "tb-1", slug: "tableau-interface", title: "Tableau Interface", durationMinutes: 9, isLocked: true },
              { id: "tb-2", slug: "connecting-data", title: "Connecting Data Sources", durationMinutes: 11, isLocked: true },
              { id: "tb-3", slug: "basic-charts", title: "Basic Charts", durationMinutes: 10, isLocked: true },
              { id: "tb-4", slug: "dashboards", title: "Dashboard Creation", durationMinutes: 13, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "machine-learning",
        slug: "machine-learning",
        title: "Machine Learning Dasar",
        lessonCount: 5,
        videoCount: 18,
        lessons: [
          {
            id: "ml-intro",
            slug: "ml-intro",
            title: "Machine Learning Introduction",
            number: 1,
            chapterCount: 3,
            studentCount: "19.456",
            rating: 4.68,
            isPortfolioProject: false,
            mentorId: "kevin-wijaya",
            chapters: [
              { id: "ml-1", slug: "supervised-learning", title: "Supervised Learning", durationMinutes: 14, isLocked: true },
              { id: "ml-2", slug: "unsupervised-learning", title: "Unsupervised Learning", durationMinutes: 12, isLocked: true },
              { id: "ml-3", slug: "model-evaluation", title: "Model Evaluation", durationMinutes: 13, isLocked: true },
            ],
          },
        ],
      },
    ],
  },

  // === Microsoft Office ===
  {
    id: "microsoft-office",
    slug: "microsoft-office",
    title: "Microsoft Office",
    topicCount: 5,
    materialCount: 68,
    description:
      "Excel mahir, PowerPoint profesional, Word untuk dokumen resmi, hingga otomasi VBA. Skill wajib untuk setiap profesional di lingkungan kerja modern.",
    tutorQuote:
      "Microsoft Office masih menjadi backbone produktivitas di ribuan perusahaan. Menguasainya secara mendalam akan membuat kamu tampil jauh lebih profesional.",
    tutorName: "Hendra Gunawan",
    tutorRole: "Microsoft Certified Trainer",
    infoCards: [
      { title: "Materi", description: "68 video mencakup Excel lanjutan, PowerPoint design, Word profesional, dan otomasi VBA." },
      { title: "Praktik", description: "Template siap pakai, latihan spreadsheet nyata, dan proyek presentasi profesional." },
      { title: "Benefit", description: "Sertifikat Jago Akademi dan template premium untuk langsung digunakan di pekerjaan." },
      { title: "Persyaratan", description: "Sudah familiar dengan komputer dasar. Microsoft Office 2019/365 diperlukan." },
    ],
    topics: [
      {
        id: "excel-mahir",
        slug: "excel-mahir",
        title: "Excel Mahir untuk Profesional",
        lessonCount: 10,
        videoCount: 32,
        lessons: [
          {
            id: "excel-formulas",
            slug: "excel-formulas",
            title: "Excel Formula Mastery",
            number: 1,
            chapterCount: 5,
            studentCount: "55.432",
            rating: 4.82,
            isPortfolioProject: false,
            mentorId: "hendra-gunawan",
            chapters: [
              { id: "ef-1", slug: "vlookup-xlookup", title: "VLOOKUP vs XLOOKUP", durationMinutes: 12, isLocked: true },
              { id: "ef-2", slug: "if-functions", title: "IF & Nested IF", durationMinutes: 10, isLocked: true },
              { id: "ef-3", slug: "index-match", title: "INDEX MATCH", durationMinutes: 11, isLocked: true },
              { id: "ef-4", slug: "pivot-tables", title: "Pivot Tables", durationMinutes: 14, isLocked: true },
              { id: "ef-5", slug: "power-query", title: "Power Query Basics", durationMinutes: 13, isLocked: true },
            ],
          },
          {
            id: "excel-dashboard",
            slug: "excel-dashboard",
            title: "Excel Dashboard",
            number: 2,
            chapterCount: 3,
            studentCount: "32.167",
            rating: 4.79,
            isPortfolioProject: true,
            mentorId: "hendra-gunawan",
            chapters: [
              { id: "ed-1", slug: "chart-design", title: "Chart Design Best Practices", durationMinutes: 11, isLocked: true },
              { id: "ed-2", slug: "interactive-dashboard", title: "Interactive Dashboard", durationMinutes: 15, isLocked: true },
              { id: "ed-3", slug: "dashboard-project", title: "Business Dashboard Project", durationMinutes: 22, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "powerpoint-pro",
        slug: "powerpoint-pro",
        title: "PowerPoint Presentasi Profesional",
        lessonCount: 7,
        videoCount: 22,
        lessons: [
          {
            id: "ppt-design",
            slug: "ppt-design",
            title: "Presentation Design Principles",
            number: 1,
            chapterCount: 4,
            studentCount: "43.789",
            rating: 4.77,
            isPortfolioProject: false,
            mentorId: "hendra-gunawan",
            chapters: [
              { id: "pd-1", slug: "slide-design", title: "Slide Design Principles", durationMinutes: 10, isLocked: true },
              { id: "pd-2", slug: "color-typography", title: "Color & Typography", durationMinutes: 9, isLocked: true },
              { id: "pd-3", slug: "storytelling-ppt", title: "Storytelling with Slides", durationMinutes: 12, isLocked: true },
              { id: "pd-4", slug: "animation-transitions", title: "Animation & Transitions", durationMinutes: 8, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "word-profesional",
        slug: "word-profesional",
        title: "Word untuk Dokumen Profesional",
        lessonCount: 5,
        videoCount: 16,
        lessons: [
          {
            id: "word-formatting",
            slug: "word-formatting",
            title: "Word Formatting Mastery",
            number: 1,
            chapterCount: 4,
            studentCount: "28.543",
            rating: 4.68,
            isPortfolioProject: false,
            mentorId: "hendra-gunawan",
            chapters: [
              { id: "wf-1", slug: "styles-templates", title: "Styles & Templates", durationMinutes: 10, isLocked: true },
              { id: "wf-2", slug: "table-of-contents", title: "Automatic Table of Contents", durationMinutes: 9, isLocked: true },
              { id: "wf-3", slug: "mail-merge", title: "Mail Merge", durationMinutes: 11, isLocked: true },
              { id: "wf-4", slug: "track-changes", title: "Track Changes & Comments", durationMinutes: 8, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "excel-vba",
        slug: "excel-vba",
        title: "Excel VBA & Macro Automation",
        lessonCount: 6,
        videoCount: 20,
        lessons: [
          {
            id: "vba-intro",
            slug: "vba-intro",
            title: "VBA Introduction",
            number: 1,
            chapterCount: 3,
            studentCount: "14.321",
            rating: 4.71,
            isPortfolioProject: false,
            mentorId: "hendra-gunawan",
            chapters: [
              { id: "vi-1", slug: "vba-editor", title: "VBA Editor Introduction", durationMinutes: 9, isLocked: true },
              { id: "vi-2", slug: "macro-recording", title: "Macro Recording", durationMinutes: 8, isLocked: true },
              { id: "vi-3", slug: "vba-basics", title: "VBA Programming Basics", durationMinutes: 12, isLocked: true },
            ],
          },
        ],
      },
    ],
  },

  // === UI/UX Research & Design ===
  {
    id: "ui-ux",
    slug: "ui-ux",
    title: "UI/UX Research & Design",
    topicCount: 6,
    materialCount: 78,
    description:
      "Dari user research, wireframing, prototyping di Figma, hingga usability testing. Bangun fondasi karier sebagai UI/UX Designer profesional.",
    tutorQuote:
      "Design bukan hanya soal estetika — ini soal memahami manusia. Kuasai skill ini dan kamu akan bisa menciptakan produk yang benar-benar dicintai penggunanya.",
    tutorName: "Cindy Maharani",
    tutorRole: "Senior Product Designer",
    infoCards: [
      { title: "Materi", description: "78 video dari design thinking, user research, Figma, hingga handoff ke developer." },
      { title: "Praktik", description: "Proyek UI/UX nyata dengan brief dari industri, portfolio case study yang siap ditampilkan." },
      { title: "Benefit", description: "Sertifikat resmi, feedback dari mentor berpengalaman, dan akses community Designer Indonesia." },
      { title: "Persyaratan", description: "Tidak perlu background design. Butuh laptop dan akses Figma (gratis tersedia)." },
    ],
    topics: [
      {
        id: "design-thinking",
        slug: "design-thinking",
        title: "Design Thinking",
        lessonCount: 5,
        videoCount: 18,
        lessons: [
          {
            id: "design-thinking-intro",
            slug: "design-thinking-intro",
            title: "Design Thinking Introduction",
            number: 1,
            chapterCount: 5,
            studentCount: "32.567",
            rating: 4.76,
            isPortfolioProject: false,
            mentorId: "cindy-maharani",
            chapters: [
              { id: "dt-1", slug: "empathize", title: "Empathize", durationMinutes: 10, isLocked: true },
              { id: "dt-2", slug: "define", title: "Define", durationMinutes: 9, isLocked: true },
              { id: "dt-3", slug: "ideate", title: "Ideate", durationMinutes: 11, isLocked: true },
              { id: "dt-4", slug: "prototype", title: "Prototype", durationMinutes: 10, isLocked: true },
              { id: "dt-5", slug: "test", title: "Test", durationMinutes: 9, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "figma-desain",
        slug: "figma-desain",
        title: "UI/UX Design dengan Figma",
        lessonCount: 8,
        videoCount: 28,
        lessons: [
          {
            id: "figma-intro",
            slug: "figma-intro",
            title: "Figma Introduction",
            number: 1,
            chapterCount: 4,
            studentCount: "45.123",
            rating: 4.80,
            isPortfolioProject: false,
            mentorId: "cindy-maharani",
            chapters: [
              { id: "fi-1", slug: "figma-interface", title: "Figma Interface", durationMinutes: 9, isLocked: true },
              { id: "fi-2", slug: "frames-layers", title: "Frames & Layers", durationMinutes: 10, isLocked: true },
              { id: "fi-3", slug: "components", title: "Components & Variants", durationMinutes: 13, isLocked: true },
              { id: "fi-4", slug: "auto-layout", title: "Auto Layout", durationMinutes: 11, isLocked: true },
            ],
          },
          {
            id: "wireframing",
            slug: "wireframing",
            title: "Wireframing & Prototyping",
            number: 2,
            chapterCount: 3,
            studentCount: "28.789",
            rating: 4.74,
            isPortfolioProject: true,
            mentorId: "cindy-maharani",
            chapters: [
              { id: "wp-1", slug: "low-fidelity", title: "Low-Fidelity Wireframes", durationMinutes: 11, isLocked: true },
              { id: "wp-2", slug: "high-fidelity", title: "High-Fidelity Mockups", durationMinutes: 14, isLocked: true },
              { id: "wp-3", slug: "prototype-project", title: "Mobile App Prototype Project", durationMinutes: 22, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "user-research",
        slug: "user-research",
        title: "User Research & Usability Testing",
        lessonCount: 6,
        videoCount: 20,
        lessons: [
          {
            id: "research-methods",
            slug: "research-methods",
            title: "Research Methods",
            number: 1,
            chapterCount: 4,
            studentCount: "21.456",
            rating: 4.73,
            isPortfolioProject: false,
            mentorId: "cindy-maharani",
            chapters: [
              { id: "rm-1", slug: "quantitative-research", title: "Quantitative Research", durationMinutes: 10, isLocked: true },
              { id: "rm-2", slug: "qualitative-research", title: "Qualitative Research", durationMinutes: 12, isLocked: true },
              { id: "rm-3", slug: "user-interviews", title: "User Interviews", durationMinutes: 13, isLocked: true },
              { id: "rm-4", slug: "surveys", title: "Survey Design", durationMinutes: 9, isLocked: true },
            ],
          },
        ],
      },
    ],
  },

  // === Product & Project Management ===
  {
    id: "product-management",
    slug: "product-management",
    title: "Product & Project Management",
    topicCount: 5,
    materialCount: 62,
    description:
      "Dari product discovery, roadmap planning, agile methodology, hingga stakeholder management. Siapkan diri sebagai Product Manager atau Project Manager andal.",
    tutorQuote:
      "Product Management adalah seni menerjemahkan kebutuhan pengguna menjadi produk yang sukses. Setiap keputusan harus berbasis data, bukan asumsi.",
    tutorName: "Tina Wulandari",
    tutorRole: "Senior Product Manager",
    infoCards: [
      { title: "Materi", description: "62 video dari product strategy, Agile/Scrum, stakeholder management, hingga product metrics." },
      { title: "Praktik", description: "PRD templates, roadmap exercises, dan studi kasus produk nyata dari startup hingga enterprise." },
      { title: "Benefit", description: "Sertifikat resmi, template PM toolkit, dan koneksi ke komunitas Product Manager Indonesia." },
      { title: "Persyaratan", description: "Tidak ada prasyarat. Cocok untuk fresh graduate, business analyst, atau developer yang ingin pivot ke PM." },
    ],
    topics: [
      {
        id: "product-fundamentals",
        slug: "product-fundamentals",
        title: "Product Management Essentials",
        lessonCount: 8,
        videoCount: 26,
        lessons: [
          {
            id: "pm-intro",
            slug: "pm-intro",
            title: "Product Management Introduction",
            number: 1,
            chapterCount: 4,
            studentCount: "28.456",
            rating: 4.75,
            isPortfolioProject: false,
            mentorId: "tina-wulandari",
            chapters: [
              { id: "pmi-1", slug: "what-is-pm", title: "What is Product Management?", durationMinutes: 10, isLocked: true },
              { id: "pmi-2", slug: "pm-vs-po", title: "PM vs PO vs BA", durationMinutes: 9, isLocked: true },
              { id: "pmi-3", slug: "product-lifecycle", title: "Product Lifecycle", durationMinutes: 11, isLocked: true },
              { id: "pmi-4", slug: "pm-tools", title: "PM Tools Overview", durationMinutes: 8, isLocked: true },
            ],
          },
          {
            id: "product-discovery",
            slug: "product-discovery",
            title: "Product Discovery",
            number: 2,
            chapterCount: 3,
            studentCount: "18.789",
            rating: 4.72,
            isPortfolioProject: false,
            mentorId: "tina-wulandari",
            chapters: [
              { id: "pd2-1", slug: "user-problem", title: "Defining User Problems", durationMinutes: 12, isLocked: true },
              { id: "pd2-2", slug: "opportunity-sizing", title: "Opportunity Sizing", durationMinutes: 10, isLocked: true },
              { id: "pd2-3", slug: "hypothesis-testing", title: "Hypothesis Testing", durationMinutes: 11, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "agile-scrum",
        slug: "agile-scrum",
        title: "Agile & Scrum untuk Tim",
        lessonCount: 7,
        videoCount: 22,
        lessons: [
          {
            id: "agile-intro",
            slug: "agile-intro",
            title: "Agile Introduction",
            number: 1,
            chapterCount: 4,
            studentCount: "22.345",
            rating: 4.73,
            isPortfolioProject: false,
            mentorId: "tina-wulandari",
            chapters: [
              { id: "ai-1", slug: "agile-manifesto", title: "Agile Manifesto", durationMinutes: 9, isLocked: true },
              { id: "ai-2", slug: "scrum-framework", title: "Scrum Framework", durationMinutes: 12, isLocked: true },
              { id: "ai-3", slug: "sprint-planning", title: "Sprint Planning", durationMinutes: 10, isLocked: true },
              { id: "ai-4", slug: "retrospective", title: "Sprint Retrospective", durationMinutes: 8, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "product-roadmap",
        slug: "product-roadmap",
        title: "Product Roadmap & Strategy",
        lessonCount: 5,
        videoCount: 16,
        lessons: [
          {
            id: "roadmap-basics",
            slug: "roadmap-basics",
            title: "Roadmap Fundamentals",
            number: 1,
            chapterCount: 3,
            studentCount: "16.543",
            rating: 4.70,
            isPortfolioProject: false,
            mentorId: "tina-wulandari",
            chapters: [
              { id: "rb-1", slug: "prioritization", title: "Feature Prioritization", durationMinutes: 12, isLocked: true },
              { id: "rb-2", slug: "roadmap-formats", title: "Roadmap Formats", durationMinutes: 10, isLocked: true },
              { id: "rb-3", slug: "stakeholder-alignment", title: "Stakeholder Alignment", durationMinutes: 11, isLocked: true },
            ],
          },
        ],
      },
    ],
  },

  // === Website & Apps Development ===
  {
    id: "web-dev",
    slug: "web-dev",
    title: "Website & Apps Development",
    topicCount: 6,
    materialCount: 88,
    description:
      "HTML, CSS, JavaScript, React.js, Node.js, hingga full stack Next.js development. Bangun portofolio developer yang memukau dan siap masuk industri tech.",
    tutorQuote:
      "Programming adalah superpower di era digital. Dengan kemampuan ini, ide apapun yang ada di kepalamu bisa kamu wujudkan menjadi produk nyata.",
    tutorName: "Gilang Permana",
    tutorRole: "Senior Full Stack Developer",
    infoCards: [
      { title: "Materi", description: "88 video dari HTML/CSS dasar, JavaScript modern, React, Node.js, hingga deployment." },
      { title: "Praktik", description: "Build 5+ proyek nyata yang langsung bisa masuk GitHub dan portfolio kamu." },
      { title: "Benefit", description: "Sertifikat resmi, code review dari mentor, dan akses komunitas Developer Indonesia." },
      { title: "Persyaratan", description: "Tidak ada prasyarat programming. Butuh laptop dengan koneksi internet dan text editor." },
    ],
    topics: [
      {
        id: "html-css-js",
        slug: "html-css-js",
        title: "HTML, CSS & JavaScript Dasar",
        lessonCount: 10,
        videoCount: 32,
        lessons: [
          {
            id: "html-basics",
            slug: "html-basics",
            title: "HTML Fundamentals",
            number: 1,
            chapterCount: 4,
            studentCount: "58.123",
            rating: 4.79,
            isPortfolioProject: false,
            mentorId: "gilang-permana",
            chapters: [
              { id: "hb-1", slug: "html-structure", title: "HTML Structure", durationMinutes: 10, isLocked: true },
              { id: "hb-2", slug: "semantic-html", title: "Semantic HTML", durationMinutes: 11, isLocked: true },
              { id: "hb-3", slug: "forms", title: "HTML Forms", durationMinutes: 9, isLocked: true },
              { id: "hb-4", slug: "html5-apis", title: "HTML5 APIs", durationMinutes: 12, isLocked: true },
            ],
          },
          {
            id: "css-styling",
            slug: "css-styling",
            title: "CSS Styling & Layout",
            number: 2,
            chapterCount: 5,
            studentCount: "41.567",
            rating: 4.76,
            isPortfolioProject: false,
            mentorId: "gilang-permana",
            chapters: [
              { id: "cs-1", slug: "flexbox", title: "Flexbox", durationMinutes: 13, isLocked: true },
              { id: "cs-2", slug: "grid", title: "CSS Grid", durationMinutes: 12, isLocked: true },
              { id: "cs-3", slug: "responsive", title: "Responsive Design", durationMinutes: 11, isLocked: true },
              { id: "cs-4", slug: "animations", title: "CSS Animations", durationMinutes: 10, isLocked: true },
              { id: "cs-5", slug: "css-project", title: "Landing Page Project", durationMinutes: 20, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "react-frontend",
        slug: "react-frontend",
        title: "React.js untuk Frontend",
        lessonCount: 8,
        videoCount: 28,
        lessons: [
          {
            id: "react-basics",
            slug: "react-basics",
            title: "React Fundamentals",
            number: 1,
            chapterCount: 4,
            studentCount: "34.789",
            rating: 4.77,
            isPortfolioProject: false,
            mentorId: "gilang-permana",
            chapters: [
              { id: "rb2-1", slug: "jsx", title: "JSX & Components", durationMinutes: 11, isLocked: true },
              { id: "rb2-2", slug: "props-state", title: "Props & State", durationMinutes: 13, isLocked: true },
              { id: "rb2-3", slug: "hooks", title: "React Hooks", durationMinutes: 14, isLocked: true },
              { id: "rb2-4", slug: "context", title: "Context API", durationMinutes: 10, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "nodejs-api",
        slug: "nodejs-api",
        title: "Node.js & Express API",
        lessonCount: 7,
        videoCount: 24,
        lessons: [
          {
            id: "node-basics",
            slug: "node-basics",
            title: "Node.js Fundamentals",
            number: 1,
            chapterCount: 4,
            studentCount: "22.456",
            rating: 4.73,
            isPortfolioProject: false,
            mentorId: "gilang-permana",
            chapters: [
              { id: "nb-1", slug: "node-intro", title: "Node.js Introduction", durationMinutes: 10, isLocked: true },
              { id: "nb-2", slug: "express-setup", title: "Express Setup", durationMinutes: 9, isLocked: true },
              { id: "nb-3", slug: "rest-api", title: "REST API Design", durationMinutes: 13, isLocked: true },
              { id: "nb-4", slug: "database-integration", title: "Database Integration", durationMinutes: 14, isLocked: true },
            ],
          },
        ],
      },
      {
        id: "nextjs-fullstack",
        slug: "nextjs-fullstack",
        title: "Next.js Full Stack Development",
        lessonCount: 9,
        videoCount: 32,
        lessons: [
          {
            id: "nextjs-basics",
            slug: "nextjs-basics",
            title: "Next.js App Router",
            number: 1,
            chapterCount: 5,
            studentCount: "18.321",
            rating: 4.80,
            isPortfolioProject: false,
            mentorId: "gilang-permana",
            chapters: [
              { id: "nj-1", slug: "app-router", title: "App Router Architecture", durationMinutes: 12, isLocked: true },
              { id: "nj-2", slug: "server-components", title: "Server Components", durationMinutes: 13, isLocked: true },
              { id: "nj-3", slug: "data-fetching", title: "Data Fetching", durationMinutes: 11, isLocked: true },
              { id: "nj-4", slug: "server-actions", title: "Server Actions", durationMinutes: 10, isLocked: true },
              { id: "nj-5", slug: "deployment", title: "Deployment to Vercel", durationMinutes: 9, isLocked: true },
            ],
          },
        ],
      },
    ],
  },
];

export const mentors: Mentor[] = [
  {
    id: "ahmad-fauzi",
    slug: "ahmad-fauzi",
    name: "Ahmad Fauzi",
    role: "Senior Digital Marketing Strategist",
    company: "Tokopedia",
    bio: "Lebih dari 10 tahun pengalaman di dunia Digital Marketing, mulai dari agency hingga perusahaan teknologi terkemuka. Ahmad telah merancang dan mengeksekusi ratusan kampanye digital yang berhasil menghasilkan jutaan rupiah revenue.",
    totalStudents: "89.2K",
    avgRating: 4.71,
    teachingHours: 248,
    linkedinUrl: "https://linkedin.com",
    topicIds: [
      "marketing-management",
      "campaign-media-planning",
      "facebook-ads",
      "google-ads",
      "google-analytics",
      "seo",
      "app-store-optimization",
      "customer-relationship-management",
    ],
  },
  {
    id: "rina-kusuma",
    slug: "rina-kusuma",
    name: "Rina Kusuma",
    role: "Brand & Content Strategist",
    company: "Gojek",
    bio: "Spesialis brand building dan content strategy dengan rekam jejak membangun brand-brand ikonik Indonesia. Rina percaya bahwa setiap brand memiliki cerita unik yang perlu disampaikan dengan cara yang tepat ke audiens yang tepat.",
    totalStudents: "62.4K",
    avgRating: 4.68,
    teachingHours: 184,
    linkedinUrl: "https://linkedin.com",
    topicIds: [
      "creative-copywriting",
      "social-media-marketing",
      "influencer-marketing",
      "customer-relationship-management",
      "tiktok-ads",
    ],
  },
  {
    id: "kevin-wijaya",
    slug: "kevin-wijaya",
    name: "Kevin Wijaya",
    role: "Senior Data Scientist",
    company: "Bank Central Asia",
    bio: "Data Scientist berpengalaman yang telah membangun model analitik untuk perusahaan Fortune 500 dan startup unicorn Indonesia. Kevin mengajarkan data science dengan pendekatan praktis berbasis studi kasus nyata.",
    totalStudents: "47.8K",
    avgRating: 4.74,
    teachingHours: 156,
    linkedinUrl: "https://linkedin.com",
    topicIds: ["python-dasar", "sql-analysis", "data-visualization", "machine-learning"],
  },
  {
    id: "hendra-gunawan",
    slug: "hendra-gunawan",
    name: "Hendra Gunawan",
    role: "Microsoft Certified Trainer",
    company: "Deloitte",
    bio: "Microsoft Certified Professional dengan sertifikasi Excel Expert dan PowerPoint Specialist. Hendra telah melatih lebih dari 50.000 profesional dalam penggunaan Microsoft Office secara efektif dan efisien.",
    totalStudents: "78.3K",
    avgRating: 4.76,
    teachingHours: 212,
    linkedinUrl: "https://linkedin.com",
    topicIds: ["excel-mahir", "powerpoint-pro", "word-profesional", "excel-vba"],
  },
  {
    id: "cindy-maharani",
    slug: "cindy-maharani",
    name: "Cindy Maharani",
    role: "Senior Product Designer",
    company: "Shopee",
    bio: "Product Designer dengan passion dalam menciptakan pengalaman digital yang intuitif dan manusiawi. Cindy memimpin tim design di beberapa produk dengan jutaan pengguna aktif dan selalu berpegang pada user-centered design principles.",
    totalStudents: "38.9K",
    avgRating: 4.77,
    teachingHours: 128,
    linkedinUrl: "https://linkedin.com",
    topicIds: ["design-thinking", "figma-desain", "user-research"],
  },
  {
    id: "tina-wulandari",
    slug: "tina-wulandari",
    name: "Tina Wulandari",
    role: "Senior Product Manager",
    company: "Bukalapak",
    bio: "Product Manager berpengalaman yang telah memimpin pengembangan produk dari 0 hingga jutaan pengguna. Tina dikenal dengan pendekatannya yang data-driven dan kemampuannya mengkoordinasikan tim lintas divisi.",
    totalStudents: "29.4K",
    avgRating: 4.73,
    teachingHours: 96,
    linkedinUrl: "https://linkedin.com",
    topicIds: ["product-fundamentals", "agile-scrum", "product-roadmap"],
  },
  {
    id: "gilang-permana",
    slug: "gilang-permana",
    name: "Gilang Permana",
    role: "Senior Full Stack Developer",
    company: "Traveloka",
    bio: "Full Stack Developer dengan spesialisasi di JavaScript ecosystem — React, Node.js, dan Next.js. Gilang telah membangun aplikasi web dan mobile yang digunakan oleh jutaan pengguna setiap harinya.",
    totalStudents: "52.1K",
    avgRating: 4.78,
    teachingHours: 176,
    linkedinUrl: "https://linkedin.com",
    topicIds: ["html-css-js", "react-frontend", "nodejs-api", "nextjs-fullstack"],
  },
];
